[package]
name = "midi2key"
version = "0.3.0"
authors = ["Seercat3160"]
description = "Bind MIDI notes to keyboard keys and mouse movement"
edition = "2021"
build = "src/build.rs"

[dependencies]
midly = "0.5"
midir = "0.8"
clap = { version = "4.0", features = ["derive", "unicode"] }
simple_logger = "4.0"
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
enigo = "0.0.14"

[build-dependencies]
winres = "0.1"
