[package]
name = "midi2key"
version = "0.5.0"
authors = ["Seercat3160"]
description = "Bind MIDI notes to keyboard keys and mouse movement"
edition = "2021"

[dependencies]


[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
