name: Build

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            os-name: Windows
            artifact-path: |
              target/release/midi2key.exe
          - os: ubuntu-latest
            os-name: Linux
            artifact-path: |
              target/release/midi2key
    
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os-name }} Build

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup install stable
      - name: Install Linux Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev 
          sudo apt-get install libxdo-dev
      - name: Check Formatting
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy --all-targets --all-features --release
      - name: Build
        run: cargo build --verbose --release
      - name: Test
        run: cargo test --verbose --release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os-name }}
          path: ${{ matrix.artifact-path }}
