name: Build

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings


jobs:
  check:
    runs-on: ubuntu-latest
    name: Check

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup install stable
      - name: Install Dependencies
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: libasound2-dev libxdo-dev libgtk-3-dev libclang-dev
      - name: Check Formatting
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy --all-targets --all-features --release
  
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            os-name: Windows
            artifact-path: |
              target/release/midi2key.exe
          - os: ubuntu-latest
            os-name: Linux
            artifact-path: |
              target/release/midi2key
          - os: macos-latest
            os-name: MacOS
            artifact-path: |
              target/release/midi2key
    
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os-name }} Build

    needs: check

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup install stable
      - name: Install Dependencies
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: libasound2-dev libxdo-dev libgtk-3-dev libclang-dev
      - name: Build
        run: cargo build --verbose --release
      - name: Test
        run: cargo test --verbose --release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os-name }}
          path: ${{ matrix.artifact-path }}
  
  release:
    if: ${{ github.ref_type == 'tag' }}

    runs-on: ubuntu-latest
    name: Release Built Artifacts

    needs: build

    permissions:
      contents: write
    
    steps:
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          body: |
            | File           | Description          | SHA-256 Checksum                                 |
            |----------------|----------------------|--------------------------------------------------|
            | `midi2key`     | Linux amd64 binary   | ${{ hashFiles('artifacts/Linux/midi2key') }}       |
            | `midi2key.exe` | Windows amd64 binary | ${{ hashFiles('artifacts/Windows/midi2key.exe') }} |
          files: |
            artifacts/Linux/midi2key
            artifacts/Windows/midi2key.exe

        
